#!/bin/bash
### BEGIN INIT INFO
# Provides:             init script for Cassandra.
# Required-Start:
# Required-Stop:
# Default-Start:        3 5
# Default-Stop:         0 1 2 6
# Short-Description:    Cassandra-Init
# Description:          Cassandra-Init
# script slightly modified from Patrick Monte (patrick.monte@mv.com.br)
# http://blog.milford.io/2010/06/installing-apache-cassandra-on-centos/
### END INIT INFO

# . /etc/rc.d/init.d/functions

###  Criar pasta mkdir /MV/apm/apache-cassandra-2.1.17/log

CASS_HOME=/MV/apm/apache-cassandra-2.1.17
CASS_BIN=$CASS_HOME/bin/cassandra
CASS_LOG=$CASS_HOME/log/system.log
CASS_USER="mv"
CASS_PID=/var/run/cassandra.pid
 
if [ ! -f $CASS_BIN ]; then
  echo "File not found: $CASS_BIN"
  exit 1
fi
 
RETVAL=0
 
start() {
  if [ -f $CASS_PID ] && checkpid `cat $CASS_PID`; then
    echo "Cassandra is already running."
    exit 0
  fi
  echo -n $"Starting $prog: "
  daemon --user $CASS_USER $CASS_BIN -p $CASS_PID >> $CASS_LOG 2>&1
  usleep 500000
  RETVAL=$?
  if [ "$RETVAL" = "0" ]; then
    echo_success
  else
    echo_failure
  fi
  echo
  return $RETVAL
}
 
stop() {
  # check if the process is already stopped by seeing if the pid file exists.
  if [ ! -f $CASS_PID ]; then
    echo "Cassandra is already stopped."
    exit 0
  fi
  echo -n $"Stopping $prog: "
  if kill `cat $CASS_PID`; then
    RETVAL=0
    echo_success
  else
    RETVAL=1
    echo_failure
  fi
  echo
  [ $RETVAL = 0 ]
}
 
status_fn() {
  if [ -f $CASS_PID ] && checkpid `cat $CASS_PID`; then
    echo "Cassandra is running."
    exit 0
  else
    echo "Cassandra is stopped."
    exit 1
  fi
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_fn
    ;;
  restart)
    stop
  usleep 500000
    start
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
    RETVAL=3
esac
 
exit $RETVAL
