#!/bin/bash
### BEGIN INIT INFO
# Provides:             Suse Init script for Cassandra.
# Required-Start:
# Required-Stop:
# Default-Start:        3 5
# Default-Stop:         0 1 2 6
# Short-Description:    Cassandra-Init-Suse
# Description:          Cassandra-Init-Suse
# script slightly modified from Patrick Monte (patrick.monte@mv.com.br)
# http://blog.milford.io/2010/06/installing-apache-cassandra-on-centos/
### END INIT INFO

# . /etc/rc.d/init.d/functions
. /etc/rc.status

## Cassandra Folder Install
CASS_HOME=/opt/apm/apache-cassandra-2.1.17
CASS_BIN=$CASS_HOME/bin/cassandra
CASS_LOG=$CASS_HOME/logs/cassandra.log
CASS_USER="cassandra"

# PID Check
cass_pid() {
    echo `ps aux | grep $CASS_HOME | grep -v grep | awk '{ print $2 }'`
}
PID=$(cass_pid)

 
if [ ! -f $CASS_BIN ]; 
then
  echo "File not found: $CASS_BIN"
  exit 1
fi
 
RETVAL=0
 
start() {
  if [ -n "$PID" ]; 
  then
    echo "Cassandra is already running (pid: $PID)."
    exit 0
  fi
  echo -n $"Starting $prog: "
  startproc -v -u $CASS_USER -l $CASS_LOG -w $CASS_BIN
  usleep 500000
  RETVAL=$?
  if [ "$RETVAL" = "0" ]; 
  then
    rc_status -v
  else
    rc_failed
  fi
  echo
  return $RETVAL
}
 
stop() {
  # check if the process is already stopped by seeing if the pid file exists.
  if [ ! -n "$PID" ]; 
  then
    echo "Cassandra is already stopped."
    exit 0
  fi
  echo -n $"Stopping $prog: "
  if kill $PID; then
    RETVAL=0
    rc_status -v
  else
    RETVAL=1
    rc_failed
  fi
  echo
  [ $RETVAL = 0 ]
}
 
status_fn() {
  if [ -n "$PID" ]; 
  then
#  if checkproc $CASS_BIN; then
    echo "Cassandra is running with pid: $PID "
    exit 0
  else
    echo "Cassandra is stopped."
    exit 1
  fi
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_fn
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
    RETVAL=3
esac
 
exit $RETVAL
